CREATE TYPE status as ENUM ('open', 'pending', 'completed');
CREATE TABLE tasks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  difficulty INTEGER NOT NULL,
  reward INTEGER NOT NULL,
  current_status status NOT NULL,
  child_id INTEGER
    REFERENCES children(id) ON DELETE CASCADE NOT NULL
);